[project]
name = "AD-Bloodhound"
version = "0.1.0"
description = "Bloodhound"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
    "termcolor>=2.3.0", 
    "pwn>=1.0.0",
    "tqdm>=4.66.1"
]